name: Violet Rhythm
favicon: null
layout_spectrum: 0.1661347895860672
typography_spectrum: 0.7862934956792742
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8394428272731602
  lightness: 0.1558313404675573
  saturation: 0.5832509319297969
  rhythmicContrast: 0.5275598953012377
purpose: []
