name: Violet Rhythm
favicon: null
layout_spectrum: 0.1661347895860672
typography_spectrum: 0.7862934956792742
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010508'
    - '#853d55'
    - '#c06f9a'
    - '#da566e'
    - '#fee5fc'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
